### ISSUE TITLE
rBRR Water Vapor, Ozone, elevation

### ISSUE THREAD

**Issue by jasonebox** [maximlamare/S3_extract#3]
I am successful to output geometry, see below, but how to get a list of available variables?

Cheers, 

Jason

Alex wants TOA reflectance and bottom or Rayleigh reflectance... dare I say he also needs Water Vapor, Ozone, elevation

python s3_band_extract.py \
	-i /Users/jason/0_dat/S3/20170722 \
	-c /Users/jason/Dropbox/S3/validation_source_data/Cook_data/stats/near_s6.csv \
	-o /Users/jason/0_dat/S3/20170722/test \
	-b SZA OZA SAA OAA

**Comment by maximlamare** [comment]
I have added a script (list_sat_bands.py) that lists the following for a specified satellite image:

- Bands
- TiePointGrids
- Masks

The script can print to screen the lists, or if a filename is specified, it will write the lists to the file.

If you are not sure of the variables to specify in _s3_band_extract.py_, you can run this tool on an image.

For S3, _bottom of Rayleigh reflectance_ is a different story because it requires a processor to be run, and the band_extract tool isn't designed for this. You can run the processor (Rad2Refl), then run the band_extract on the saved product, that should work.

No problems for extracting the other variables you mention.
